<?xml version="1.0" encoding="utf-8"?><Database Name="Laquev_timesheet_management" Class="LTSMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DB;Initial Catalog=Laquev_timesheet_management;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Laquev_timesheet_managementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblJob_Title" Member="tblJob_Titles">
    <Type Name="tblJob_Title">
      <Column Name="Job_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Job_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nakfa_per_hr" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tblJob_Title_tblStaff_info" Member="tblStaff_infos" ThisKey="Job_id" OtherKey="Jop_id" Type="tblStaff_info" />
    </Type>
  </Table>
  <Table Name="dbo.tblStaff_info" Member="tblStaff_infos">
    <Type Name="tblStaff_info">
      <Column Name="Staff_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Phone_number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Join_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Profession" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Jop_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Del_status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Hrs_per_day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblStaff_info_tblTime_Record" Member="tblTime_Records" ThisKey="Staff_id" OtherKey="Staff_id" Type="tblTime_Record" />
      <Association Name="tblJob_Title_tblStaff_info" Member="tblJob_Title" ThisKey="Jop_id" OtherKey="Job_id" Type="tblJob_Title" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Authenticate_user" Member="Authenticate_users">
    <Type Name="Authenticate_user">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblTime_Record" Member="tblTime_Records">
    <Type Name="tblTime_Record">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Staff_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Week_id" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Day_status" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Total_per_day" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="tblStaff_info_tblTime_Record" Member="tblStaff_info" ThisKey="Staff_id" OtherKey="Staff_id" Type="tblStaff_info" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.report" Method="report">
    <ElementType Name="reportResult">
      <Column Name="Fname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Profession" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Total_per_day" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>